## First Look at numpy

Python does not have any native support for arrays, so is less than optimal for scientific computing. However, there is an excellent third-party array package for Python called *numpy.* Previously there were two competing packages called *numeric* and *numarray*. Numpy is in some ways a merge of the two.

*Numpy* will form the backbone of much of what we do in this class and will make more sense after we talk about collections and we will revisit *numpy* in more detail after introducing collections

We gain access to numpy by importing it into our program. It is very common to *rename* numpy to np during the import.


In [2]:
import numpy as np

Numpy arrays are collections of numbers that can be manipulated efficiently. The arrays have a *type* that specifies what the underlying representation of the number is. These types include the following integers:

* uint8 (unsigned integer represented with 8 bits)
* uint16 (unsigned integer represented with 16 bits)
* uint32 (unsigned integer represented with 32 bits)
* uint64 (unsigned integer represented with 64 bits)
* int8 (unsigned integer represented with 8 bits)
* int16 (unsigned integer represented with 16 bits)
* int32 (unsigned integer represented with 32 bits)
* int64 (unsigned integer represented with 64 bits)

### What is up with all these different types?
* Memory allocation
    * If you have a very big array, memory constraints might come into play
* Computational efficiency
    * What size matches the underlying hardware?
* Maximum integer size
    * What is the minimum and maximum integer that can be represented with a uint8 and a int8?

In [3]:
a = np.array([-128,127],dtype=np.int8)
print(a)
b = np.array([-1,258],dtype=np.uint8)
print(b)

[-128  127]
[255   2]


Note that there can be some very funky and unexpected behaviors here that can cause your code to do unexpected things.
Here are the floating point and complex array types
* float16
* float32
* float64
* float128
* complex64
* complex128
* complex256

What would drive your selection of the different float or complex array sizes?

Numpy arrays are also characterized by their *shape* and their number of dimensions (*ndim*)


In [4]:
print(b.ndim,b.shape)

1 (2,)


In [5]:
c = np.array([[1,2],[3,4]])
print(c.ndim,c.shape,c.dtype)
print(c)
d = np.arange(27).reshape((3,3,3))
print(d.ndim,d.shape)
print(d)

2 (2, 2) int64
[[1 2]
 [3 4]]
3 (3, 3, 3)
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


Arrays can be added together, provided their shapes match, and also have operations applied element by element

In [6]:
print(d**2)
print(d**2+d)
print(d**2+c)

[[[  0   1   4]
  [  9  16  25]
  [ 36  49  64]]

 [[ 81 100 121]
  [144 169 196]
  [225 256 289]]

 [[324 361 400]
  [441 484 529]
  [576 625 676]]]
[[[  0   2   6]
  [ 12  20  30]
  [ 42  56  72]]

 [[ 90 110 132]
  [156 182 210]
  [240 272 306]]

 [[342 380 420]
  [462 506 552]
  [600 650 702]]]


ValueError: operands could not be broadcast together with shapes (3,3,3) (2,2) 

There is a more detailed numpy tutorial avaialble as a IPython notebook [here](http://nbviewer.ipython.org/github/jrjohansson/scientific-python-lectures/blob/master/Lecture-2-Numpy.ipynb).